module.exports={
    GET_ALL_GROUPS : 'GET_ALL_GROUPS',
    GET_GROUP_BY_ID : 'GET_GROUP_BY_ID',
    DELETE_GROUP_BY_ID : 'DELETE_GROUP_BY_ID',
    CREATE_GROUP : 'CREATE_GROUP',
    UPDATE_GROUP : 'UPDATE_GROUP',
}
